#!/bin/bash

jupyter labextension install --clean \
                            @jupyter-widgets/jupyterlab-manager \
                            dask-labextension \
                            @pyviz/jupyterlab_pyviz

# add SZ
mkdir -p ${HOME}/pysz_tmp/
git clone https://github.com/szcompressor/SZ.git ${HOME}/pysz_tmp/SZ
cd ${HOME}/pysz_tmp/SZ
conda activate notebook
mkdir build
cd build
cmake .. -DBUILD_PYTHON_WRAPPER=ON -DCMAKE_INSTALL_PREFIX:PATH=${HOME}/pysz
cmake --build .
cmake --install .

#EOF
